quarkus.application.name=inventory-management

quarkus.datasource.db-kind=postgresql


quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.http.host=0.0.0.0

quarkus.smallrye-openapi.info-title=Smart Inventory API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API for inventory management and production optimization.
quarkus.swagger-ui.always-include=true

quarkus.jackson.serialization-inclusion=non-null
